from __future__ import annotations

HOSPITAL_HEALTH_SOURCE_DEFINITIONS = [
    {
        "name": "AO Alessandria - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://concorsi.ospedale.al.it/",
        "region": "Piemonte",
        "organization": "Azienda Ospedaliera di Alessandria",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Portale pubblico concorsi verificato; usa pagine HTML di dettaglio.",
    },
    {
        "name": "IRCCS Gaslini - Lavora con noi",
        "source_type": "hospital-html-hub",
        "base_url": "https://amministrazione-trasparente.gaslini.org/amministrazione-trasparente/bandi-di-concorso-bis/concorsi/publiccompetitions/",
        "region": "Liguria",
        "organization": "IRCCS Istituto Giannina Gaslini",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": (
            "Portale ufficiale dei concorsi attivi; collega anche avvisi, mobilita, "
            "borse e collaborazioni libero-professionali."
        ),
    },
    {
        "name": "Policlinico San Martino - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ospedalesanmartino.it/it/bandi",
        "region": "Liguria",
        "organization": "IRCCS Ospedale Policlinico San Martino",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare per adapter dedicato.",
    },
    {
        "name": "Azienda Ospedale Universita Padova - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aopd.veneto.it/sez,617",
        "region": "Veneto",
        "organization": "Azienda Ospedale Universita Padova",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera; verificare formato prima dell'import.",
    },
    {
        "name": "AOUI Verona - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aovr.veneto.it/concorsi-e-avvisi",
        "region": "Veneto",
        "organization": "Azienda Ospedaliera Universitaria Integrata Verona",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": (
            "Fonte pubblica ospedaliera; concorsi spesso coordinati con Azienda Zero."
        ),
    },
    {
        "name": "IOV Veneto - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ioveneto.it/concorsi-e-avvisi/",
        "region": "Veneto",
        "organization": "Istituto Oncologico Veneto IRCCS",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Archivio ufficiale strutturato di concorsi e avvisi IOV.",
    },
    {
        "name": "IRCCS Burlo Garofolo - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.burlo.trieste.it/amministrazione-trasparente/bandi-concorso",
        "region": "Friuli-Venezia Giulia",
        "organization": "IRCCS Burlo Garofolo",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica IRCCS da verificare.",
    },
    {
        "name": "CRO Aviano - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.cro.sanita.fvg.it/it/concorsi/",
        "region": "Friuli-Venezia Giulia",
        "organization": "Centro di Riferimento Oncologico di Aviano IRCCS",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica IRCCS da verificare.",
    },
    {
        "name": "AOU Careggi - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aou-careggi.toscana.it/internet/professionisti/concorsi/",
        "region": "Toscana",
        "organization": "AOU Careggi",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte ospedaliera; in Toscana deduplicare con ESTAR.",
    },
    {
        "name": "AOU Meyer - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.meyer.it/index.php/amministrazione-trasparente/bandi-di-concorso",
        "region": "Toscana",
        "organization": "AOU Meyer IRCCS",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte ospedaliera pediatrica; deduplicare con ESTAR.",
    },
    {
        "name": "AOUP Pisa - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ao-pisa.toscana.it/index.php?option=com_content&view=article&id=226&Itemid=120",
        "region": "Toscana",
        "organization": "Azienda Ospedaliero Universitaria Pisana",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte ospedaliera; deduplicare con ESTAR.",
    },
    {
        "name": "AOU Siena - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ao-siena.toscana.it/avvisi-e-bandi/",
        "region": "Toscana",
        "organization": "Azienda Ospedaliero Universitaria Senese",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte ospedaliera; deduplicare con ESTAR.",
    },
    {
        "name": "AOU Perugia - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ospedale.perugia.it/pagine/concorsi",
        "region": "Umbria",
        "organization": "Azienda Ospedaliera di Perugia",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AO Terni - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aospterni.it/concorsi",
        "region": "Umbria",
        "organization": "Azienda Ospedaliera Santa Maria di Terni",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AOU Marche - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ospedaliriuniti.marche.it/portale/index.php/concorsi",
        "region": "Marche",
        "organization": "Azienda Ospedaliero Universitaria delle Marche",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "INRCA - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": (
            "https://www.inrca.it/INRCA/MODTRASP52/"
            "?Pag=tra_Isti_Concorsi_EspletatiX&mnu=78"
        ),
        "region": "Marche",
        "organization": "INRCA IRCCS",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica IRCCS geriatrico da verificare.",
    },
    {
        "name": "San Camillo Forlanini - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.scamilloforlanini.rm.it/concorsi/",
        "region": "Lazio",
        "organization": "Azienda Ospedaliera San Camillo Forlanini",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "IFO Roma - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://ifo.portaletrasparenza.net/it/trasparenza/bandi-di-concorso.html",
        "region": "Lazio",
        "organization": "Istituti Fisioterapici Ospitalieri IRCCS",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica IRCCS da verificare.",
    },
    {
        "name": "AORN Moscati Avellino - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aornmoscati.it/concorsi/",
        "region": "Campania",
        "organization": "AORN San Giuseppe Moscati Avellino",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AOU Federico II - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.policlinico.unina.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/1724",
        "region": "Campania",
        "organization": "AOU Federico II",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica universitaria ospedaliera da verificare.",
    },
    {
        "name": "AOR San Carlo Potenza - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ospedalesancarlo.it/amministrazione-trasparente/bandi-di-concorso/",
        "region": "Basilicata",
        "organization": "Azienda Ospedaliera Regionale San Carlo",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AO Cosenza - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://aocosenza.it/bandi/concorsi/",
        "region": "Calabria",
        "organization": "Azienda Ospedaliera di Cosenza",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AOU Renato Dulbecco - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aourenatodulbecco.it/bandi-e-concorsi/",
        "region": "Calabria",
        "organization": "AOU Renato Dulbecco",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "GOM Reggio Calabria - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": (
            "https://www.gomrc.it/doc/amministrazione-trasparente/"
            "bandi-di-concorso.html"
        ),
        "region": "Calabria",
        "organization": "Grande Ospedale Metropolitano Reggio Calabria",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AO Cannizzaro Catania - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aocannizzaro.it/selezioni/",
        "region": "Sicilia",
        "organization": "Azienda Ospedaliera Cannizzaro",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "ARNAS Garibaldi Catania - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.ao-garibaldi.ct.it/concorsi",
        "region": "Sicilia",
        "organization": "ARNAS Garibaldi Catania",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AO Papardo Messina - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://papardo.trasparenza-valutazione-merito.it/",
        "region": "Sicilia",
        "organization": "Azienda Ospedaliera Papardo",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AO Brotzu - Bandi di concorso",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aobrotzu.it/index.php?xsl=7&s=9&v=9&c=326",
        "region": "Sardegna",
        "organization": "ARNAS G. Brotzu",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica ospedaliera da verificare.",
    },
    {
        "name": "AOU Cagliari - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aoucagliari.it/home/it/concorsi.page",
        "region": "Sardegna",
        "organization": "AOU Cagliari",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica universitaria ospedaliera da verificare.",
    },
    {
        "name": "AOU Sassari - Concorsi",
        "source_type": "hospital-html-hub",
        "base_url": "https://www.aousassari.it/index.php?xsl=7&s=11&v=9&c=287",
        "region": "Sardegna",
        "organization": "AOU Sassari",
        "import_method": "hospital-html-hub-pending-adapter",
        "technical_notes": "Fonte pubblica universitaria ospedaliera da verificare.",
    },
]
