from __future__ import annotations

# Additional territorial health sources that complete the national ASL/AUSL/AULSS
# coverage when no already-active regional hub is the only prudent source.
VENETO_CENTRALIZED_NOTE = (
    "Fonte aziendale ufficiale; concorsi coperti anche da Azienda Zero Veneto."
)

NATIONAL_HEALTH_SOURCE_DEFINITIONS = [
    {
        "name": "ASL Avezzano Sulmona L'Aquila - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asl1abruzzo.it/?s=psicolog",
        "region": "Abruzzo",
        "organization": "ASL Avezzano Sulmona L'Aquila",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASL 1 Abruzzo.",
    },
    {
        "name": "ASL Pescara - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.ausl.pe.it/?s=psicolog",
        "region": "Abruzzo",
        "organization": "ASL Pescara",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASL Pescara.",
    },
    {
        "name": "ASM Matera - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asmbasilicata.it/?s=psicolog",
        "region": "Basilicata",
        "organization": "ASM Matera",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale dell'azienda sanitaria.",
    },
    {
        "name": "ASP Catanzaro - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asp.cz.it/?s=psicolog",
        "region": "Calabria",
        "organization": "ASP Catanzaro",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Cosenza - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asp.cosenza.it/?s=psicolog",
        "region": "Calabria",
        "organization": "ASP Cosenza",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Reggio Calabria - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asp.rc.it/?s=psicolog",
        "region": "Calabria",
        "organization": "ASP Reggio Calabria",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASL Napoli 2 Nord - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.aslnapoli2nord.it/?s=psicolog",
        "region": "Campania",
        "organization": "ASL Napoli 2 Nord",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASL.",
    },
    {
        "name": "ASL Salerno - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.aslsalerno.it/?s=psicolog",
        "region": "Campania",
        "organization": "ASL Salerno",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASL.",
    },
    {
        "name": "AUSL Bologna - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.ausl.bologna.it/?s=psicolog",
        "region": "Emilia-Romagna",
        "organization": "AUSL Bologna",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale AUSL.",
    },
    {
        "name": "AUSL Parma - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.ausl.pr.it/?s=psicolog",
        "region": "Emilia-Romagna",
        "organization": "AUSL Parma",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale AUSL.",
    },
    {
        "name": "AUSL Reggio Emilia - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.ausl.re.it/?s=psicolog",
        "region": "Emilia-Romagna",
        "organization": "AUSL Reggio Emilia",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale AUSL.",
    },
    {
        "name": "AUSL Toscana Centro - Concorsi",
        "source_type": "html-hub",
        "base_url": "https://www.uslcentro.toscana.it/bandi-concorsi-avvisi",
        "region": "Toscana",
        "organization": "AUSL Toscana Centro",
        "import_method": "html-hub-regional-centralized",
        "technical_notes": (
            "Fonte aziendale ufficiale. I concorsi sanitari toscani sono coperti "
            "anche dalla fonte centralizzata ESTAR."
        ),
    },
    {
        "name": "AUSL Toscana Nord Ovest - Bandi e concorsi",
        "source_type": "html-hub",
        "base_url": "https://www.uslnordovest.toscana.it/avvisi-bandi-concorsi",
        "region": "Toscana",
        "organization": "AUSL Toscana Nord Ovest",
        "import_method": "html-hub-regional-centralized",
        "technical_notes": (
            "Fonte aziendale ufficiale. I concorsi sanitari toscani sono coperti "
            "anche dalla fonte centralizzata ESTAR."
        ),
    },
    {
        "name": "AUSL Toscana Sud Est - Bandi e concorsi",
        "source_type": "html-hub",
        "base_url": "https://www.uslsudest.toscana.it/bandi-e-avvisi",
        "region": "Toscana",
        "organization": "AUSL Toscana Sud Est",
        "import_method": "html-hub-regional-centralized",
        "technical_notes": (
            "Fonte aziendale ufficiale. I concorsi sanitari toscani sono coperti "
            "anche dalla fonte centralizzata ESTAR."
        ),
    },
    {
        "name": "AULSS 1 Dolomiti - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss1.veneto.it/concorsi-e-avvisi",
        "region": "Veneto",
        "organization": "AULSS 1 Dolomiti",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 2 Marca Trevigiana - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss2.veneto.it/bandi-di-concorso",
        "region": "Veneto",
        "organization": "AULSS 2 Marca Trevigiana",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 3 Serenissima - Concorsi e avvisi",
        "source_type": "html-list",
        "base_url": "https://www.aulss3.veneto.it/concorsi-e-avvisi",
        "region": "Veneto",
        "organization": "AULSS 3 Serenissima",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 4 Veneto Orientale - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss4.veneto.it/concorsi",
        "region": "Veneto",
        "organization": "AULSS 4 Veneto Orientale",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 5 Polesana - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss5.veneto.it/bandi-di-concorso",
        "region": "Veneto",
        "organization": "AULSS 5 Polesana",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 6 Euganea - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss6.veneto.it/bandi-di-concorso",
        "region": "Veneto",
        "organization": "AULSS 6 Euganea",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 7 Pedemontana - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss7.veneto.it/avvisi-e-concorsi",
        "region": "Veneto",
        "organization": "AULSS 7 Pedemontana",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 8 Berica - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss8.veneto.it/concorsi-e-avvisi",
        "region": "Veneto",
        "organization": "AULSS 8 Berica",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "AULSS 9 Scaligera - Concorsi",
        "source_type": "html-list",
        "base_url": "https://www.aulss9.veneto.it/bandi-di-concorso",
        "region": "Veneto",
        "organization": "AULSS 9 Scaligera",
        "import_method": "html-list-regional-centralized",
        "technical_notes": VENETO_CENTRALIZED_NOTE,
    },
    {
        "name": "ASL Sassari - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl1sassari.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Sassari",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Gallura - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl2gallura.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Gallura",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Nuoro - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl3nuoro.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Nuoro",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Ogliastra - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl4ogliastra.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Ogliastra",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Oristano - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl5oristano.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Oristano",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Medio Campidano - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl6mediocampidano.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Medio Campidano",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Sulcis - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl7sulcis.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Sulcis",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASL Cagliari - Bandi di concorso e selezione",
        "source_type": "html-list",
        "base_url": "https://www.asl8cagliari.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "ASL Cagliari",
        "import_method": "html-list-regional-centralized",
        "technical_notes": "Fonte aziendale ufficiale; bandi coperti anche da ARES Sardegna.",
    },
    {
        "name": "ASP Agrigento - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.aspag.it/?s=psicolog",
        "region": "Sicilia",
        "organization": "ASP Agrigento",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Catania - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.aspct.it/?s=psicolog",
        "region": "Sicilia",
        "organization": "ASP Catania",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Palermo - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asppalermo.org/?s=psicolog",
        "region": "Sicilia",
        "organization": "ASP Palermo",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Ragusa - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asp.rg.it/?s=psicolog",
        "region": "Sicilia",
        "organization": "ASP Ragusa",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
    {
        "name": "ASP Trapani - Ricerca concorsi psicologia",
        "source_type": "html-list",
        "base_url": "https://www.asptrapani.it/?s=psicolog",
        "region": "Sicilia",
        "organization": "ASP Trapani",
        "import_method": "html-list-search",
        "technical_notes": "Ricerca pubblica sul sito ufficiale ASP.",
    },
]

NON_AUTOMATED_HEALTH_SOURCE_DEFINITIONS = [
    {
        "name": "ASL BI - Bandi concorso reclutamento personale",
        "base_url": "https://trasparenza.aslbi.piemonte.it/bandi-concorso-reclutamento-personale?sf=102",
        "region": "Piemonte",
        "organization": "ASL BI",
        "reason": "Verifica manuale: robots.txt vieta il crawl delle procedure.",
    },
    {
        "name": "Azienda Zero Calabria",
        "base_url": "",
        "region": "Calabria",
        "organization": "Azienda Zero Calabria",
        "reason": (
            "Equivalente regionale individuato, ma nessuna fonte concorsi pubblica "
            "stabile e risolvibile e stata confermata per import automatico."
        ),
    },
    {
        "name": "ASP Vibo Valentia - Ricerca concorsi psicologia",
        "base_url": "https://www.aspvv.it/?s=psicolog",
        "region": "Calabria",
        "organization": "ASP Vibo Valentia",
        "reason": (
            "Verifica manuale: il portale risponde 403 agli accessi automatici; "
            "serve un endpoint o adapter compatibile."
        ),
    },
]
