from __future__ import annotations

TARGET_HEALTH_SOURCE_DEFINITIONS = [
    {
        "name": "AUSL Modena - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.ausl.mo.it/concorsi-e-avvisi/bandi-di-concorso-archivio/",
        "region": "Emilia-Romagna",
        "organization": "AUSL Modena",
        "import_method": "target-health-html-detail",
        "technical_notes": "Archivio pubblico AUSL con schede HTML e allegati.",
    },
    {
        "name": "AUSL Piacenza - Bandi avvisi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.ausl.pc.it/it/azienda/bandi-e-concorsi",
        "region": "Emilia-Romagna",
        "organization": "AUSL Piacenza",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale con bandi, avvisi e concorsi.",
    },
    {
        "name": "AUSL Imola - Concorsi aperti",
        "source_type": "target-health-html",
        "base_url": "https://www.ausl.imola.bo.it/bandi-concorso/concorsi-aperti",
        "region": "Emilia-Romagna",
        "organization": "AUSL Imola",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica dei bandi aperti e graduatorie.",
    },
    {
        "name": "AUSL Ferrara - Bandi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.ausl.fe.it/amministrazione/bandi-e-concorsi",
        "region": "Emilia-Romagna",
        "organization": "AUSL Ferrara",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale con bandi e concorsi.",
    },
    {
        "name": "AOU Parma - Selezioni e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.ao.pr.it/asp/lavoro/bandi-personale.asp",
        "region": "Emilia-Romagna",
        "organization": "Azienda Ospedaliero-Universitaria di Parma",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica ospedaliera per bandi del personale.",
    },
    {
        "name": "AOU Modena - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.aou.mo.it/bandi",
        "region": "Emilia-Romagna",
        "organization": "Azienda Ospedaliero-Universitaria di Modena",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica ospedaliera dei bandi di concorso.",
    },
    {
        "name": "AOU Bologna Sant'Orsola - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": (
            "https://www.aosp.bo.it/il-policlinico/amministrazione-trasparente/"
            "bandi-di-concorso"
        ),
        "region": "Emilia-Romagna",
        "organization": "AOU Bologna Sant'Orsola",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica di Amministrazione Trasparente.",
    },
    {
        "name": "ESTAR Toscana - Ricerca concorsi psicologia",
        "source_type": "target-health-html",
        "base_url": "https://www.estar.toscana.it/?s=psicolog",
        "region": "Toscana",
        "organization": "ESTAR Toscana",
        "import_method": "target-health-html-search",
        "technical_notes": (
            "Ricerca pubblica WordPress ESTAR. Il REST anonimo risulta chiuso, "
            "ma la ricerca HTML pubblica restituisce schede e link ufficiali."
        ),
    },
    {
        "name": "ASL Roma 1 - Concorsi e avvisi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslroma1.it/concorsi-e-avvisi",
        "region": "Lazio",
        "organization": "ASL Roma 1",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica con elenco esteso di concorsi e avvisi.",
    },
    {
        "name": "ASL Roma 3 - Concorsi e avvisi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslroma3.it/concorsi-e-avvisi/",
        "region": "Lazio",
        "organization": "ASL Roma 3",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica e collegamento al portale Concorsi Smart.",
    },
    {
        "name": "ASL Roma 4 - Concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslroma4.it/concorsi/",
        "region": "Lazio",
        "organization": "ASL Roma 4",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale dei concorsi.",
    },
    {
        "name": "ASL Roma 5 - Concorsi e selezioni",
        "source_type": "target-health-html",
        "base_url": "https://www.aslroma5.it/amministrazione-trasparente/concorsi-e-selezioni/",
        "region": "Lazio",
        "organization": "ASL Roma 5",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica Amministrazione Trasparente con bandi e selezioni.",
    },
    {
        "name": "ASL Roma 6 - Avvisi e concorsi attivi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslroma6.it/bandi-e-concorsi/avvisi-e-concorsi-attivi",
        "region": "Lazio",
        "organization": "ASL Roma 6",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica aziendale bandi e concorsi attivi.",
    },
    {
        "name": "ASL Viterbo - Concorsi e gare",
        "source_type": "target-health-html",
        "base_url": "https://www.asl.vt.it/concorsi-e-gare",
        "region": "Lazio",
        "organization": "ASL Viterbo",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica concorsi e gare del sito aziendale.",
    },
    {
        "name": "ASL Latina - Avvisi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.ausl.latina.it/concorsi",
        "region": "Lazio",
        "organization": "ASL Latina",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica per avvisi e concorsi con sezioni annuali.",
    },
    {
        "name": "ASL Rieti - Concorsi e selezioni",
        "source_type": "target-health-html",
        "base_url": "https://www.asl.rieti.it/bandi-e-concorsi/avvisi-e-concorsi/",
        "region": "Lazio",
        "organization": "ASL Rieti",
        "import_method": "target-health-html-detail",
        "technical_notes": "Hub pubblico bandi, avvisi, concorsi e selezioni.",
    },
    {
        "name": "ASL Frosinone - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.asl.fr.it/bandi/bandi-di-concorso/",
        "region": "Lazio",
        "organization": "ASL Frosinone",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica bandi di concorso del sito aziendale.",
    },
    {
        "name": "ASL Napoli 3 Sud - Concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslnapoli3sud.it/concorsi/",
        "region": "Campania",
        "organization": "ASL Napoli 3 Sud",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica con avvisi, concorsi e scadenze.",
    },
    {
        "name": "ASL Napoli 1 Centro - Bandi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslnapoli1centro.it/bandi-e-concorsi",
        "region": "Campania",
        "organization": "ASL Napoli 1 Centro",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale bandi e concorsi.",
    },
    {
        "name": "ASL Caserta - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.aslcaserta.it/index.php/bandi-di-concorso/",
        "region": "Campania",
        "organization": "ASL Caserta",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale bandi di concorso.",
    },
    {
        "name": "ASL Benevento - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.enti33.it/ASLBENEVENTO/Menu/14/275",
        "region": "Campania",
        "organization": "ASL Benevento",
        "import_method": "target-health-html-detail",
        "technical_notes": "Portale trasparenza pubblico collegato dal sito ASL Benevento.",
    },
    {
        "name": "ASL Avellino - Concorsi e avvisi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslavellino.it/index.php/it/concorsi-e-avvisi",
        "region": "Campania",
        "organization": "ASL Avellino",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica aziendale per concorsi e avvisi.",
    },
    {
        "name": "AORN Cardarelli - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": (
            "https://aocardarelli.portaleamministrazionetrasparente.it/"
            "pagina639_bandi-di-concorso.html"
        ),
        "region": "Campania",
        "organization": "AORN Cardarelli",
        "import_method": "target-health-html-detail",
        "technical_notes": "Portale pubblico Amministrazione Trasparente.",
    },
    {
        "name": "AORN Cardarelli - Concorsi attivi",
        "source_type": "target-health-html",
        "base_url": (
            "https://aocardarelli.portaleamministrazionetrasparente.it/"
            "pagina640_concorsi-attivi.html"
        ),
        "region": "Campania",
        "organization": "AORN Cardarelli",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica dei concorsi attivi.",
    },
    {
        "name": "ASL Lecce - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.sanita.puglia.it/web/asl-lecce/bandi-di-concorso",
        "region": "Puglia",
        "organization": "ASL Lecce",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica PugliaSalute Amministrazione Trasparente.",
    },
    {
        "name": "ASL Bari - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.sanita.puglia.it/web/asl-bari/bandi-di-concorso",
        "region": "Puglia",
        "organization": "ASL Bari",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica PugliaSalute Amministrazione Trasparente.",
    },
    {
        "name": "ASL Taranto - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.sanita.puglia.it/web/asl-taranto/bandi-di-concorso",
        "region": "Puglia",
        "organization": "ASL Taranto",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica PugliaSalute Amministrazione Trasparente.",
    },
    {
        "name": "ASL Brindisi - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.sanita.puglia.it/web/asl-brindisi/bandi-di-concorso",
        "region": "Puglia",
        "organization": "ASL Brindisi",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica PugliaSalute Amministrazione Trasparente.",
    },
    {
        "name": "ASP Basilicata - Ricerca avvisi psicologici",
        "source_type": "target-health-html",
        "base_url": "https://www.aspbasilicata.it/?s=psicolog",
        "region": "Basilicata",
        "organization": "ASP Basilicata",
        "import_method": "target-health-html-search",
        "technical_notes": "Ricerca pubblica WordPress mirata ai profili psicologici.",
    },
    {
        "name": "ASL Teramo - Concorsi e avvisi",
        "source_type": "target-health-html",
        "base_url": "https://www.aslteramo.it/concorsi-ed-avvisi/",
        "region": "Abruzzo",
        "organization": "ASL Teramo",
        "import_method": "target-health-html-detail",
        "technical_notes": "Hub pubblico con procedure di selezione e avvisi.",
    },
    {
        "name": "ASL Lanciano Vasto Chieti - Avvisi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://documentale.asl2abruzzo.it/L190/?idSezione=66",
        "region": "Abruzzo",
        "organization": "ASL Lanciano Vasto Chieti",
        "import_method": "target-health-html-detail",
        "technical_notes": "Portale documentale pubblico L190 indicato dal sito aziendale.",
    },
    {
        "name": "ASReM Molise - Concorsi e avvisi",
        "source_type": "target-health-html",
        "base_url": "https://www.asrem.molise.it/concorsi-avvisi/",
        "region": "Molise",
        "organization": "ASReM Molise",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica dell'Azienda Sanitaria Regionale del Molise.",
    },
    {
        "name": "ASP Crotone - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://asp.crotone.it/bandi-di-concorso/",
        "region": "Calabria",
        "organization": "ASP Crotone",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica di Amministrazione Trasparente dell'ASP Crotone.",
    },
    {
        "name": "ASP Messina - Bandi e concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.asp.messina.it/asp-comunica/bandi-e-concorsi/?bandotype=Bando",
        "region": "Sicilia",
        "organization": "ASP Messina",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica bandi e concorsi del portale ASP Messina.",
    },
    {
        "name": "ASP Enna - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.aspenna.it/amministrazione-trasparente/bandi-di-concorso",
        "region": "Sicilia",
        "organization": "ASP Enna",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica Amministrazione Trasparente con bandi e avvisi.",
    },
    {
        "name": "ARNAS Civico Palermo - Concorsi",
        "source_type": "target-health-html",
        "base_url": "https://www.arnascivico.it/index.php/concorsi",
        "region": "Sicilia",
        "organization": "ARNAS Civico Palermo",
        "import_method": "target-health-html-detail",
        "technical_notes": "Pagina pubblica concorsi del sito aziendale.",
    },
    {
        "name": "Policlinico Catania - Bandi di concorso archivio",
        "source_type": "target-health-html",
        "base_url": "https://archivio.policlinicovittorioemanuele.it/bandi-di-concorso/",
        "region": "Sicilia",
        "organization": "Policlinico Catania",
        "import_method": "target-health-html-detail",
        "technical_notes": "Archivio pubblico dei bandi di concorso.",
    },
    {
        "name": "ASP Siracusa - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.asp.sr.it/Amministrazione-Trasparente/Bandi-di-concorso",
        "region": "Sicilia",
        "organization": "ASP Siracusa",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica Amministrazione Trasparente con bandi di concorso.",
    },
    {
        "name": "ASP Caltanissetta - Bandi di concorso",
        "source_type": "target-health-html",
        "base_url": "https://www.asp.cl.it/it/amministrazione-trasparente/bandi-di-concorso",
        "region": "Sicilia",
        "organization": "ASP Caltanissetta",
        "import_method": "target-health-html-detail",
        "technical_notes": "Sezione pubblica Drupal di Amministrazione Trasparente.",
    },
    {
        "name": "AREUS Sardegna - Bandi di concorso e selezione",
        "source_type": "target-health-html",
        "base_url": "https://www.areus.sardegna.it/albo-pretorio/bandi-di-concorso-e-selezione/",
        "region": "Sardegna",
        "organization": "AREUS Sardegna",
        "import_method": "target-health-html-detail",
        "technical_notes": (
            "Pagina pubblica con ricerca, stati, scadenze e documenti dei bandi "
            "dell'azienda regionale emergenza urgenza."
        ),
    },
    {
        "name": "ARES Sardegna - Ricerca bandi psicologia",
        "source_type": "target-health-html",
        "base_url": "https://www.aressardegna.it/?s=psicolog",
        "region": "Sardegna",
        "organization": "ARES Sardegna",
        "import_method": "target-health-html-search",
        "technical_notes": (
            "Ricerca pubblica WordPress e sitemap aperta. Copre albo pretorio, "
            "bandi di concorso e selezione dell'azienda regionale salute."
        ),
    },
]
